export const USERS_FETCH_REQUESTED = 'USERS_FETCH_REQUESTED';
export const USERS_FETCH_SUCCEEDED = 'USERS_FETCH_SUCCEEDED';
export const USERS_FETCH_FAILED = 'USERS_FETCH_FAILED';
export const USERS_RECORD_TO_DISPLAY = 'USERS_RECORD_TO_DISPLAY';
export const RESET_USERS_FETCH_FAILED = 'RESET_USERS_FETCH_FAILED';
export const RESET_USERS_LIST = 'RESET_USERS_LIST';
export const SET_USERS_SEARCH = 'SET_USERS_SEARCH';
export const SET_NATIONALITY_SEARCH = 'SET_NATIONALITY_SEARCH';
